const ificationContent = [
  {
    title:"难度",
    content:[
      {text:"全部"},
      {text:"入门"},
      {text:"进阶"},
      {text:"适中"},
      {text:"烧脑"},
      {text:"撕本"}
    ]
  },
  {
    title:"人数",
    content:[
      {text:"全部"},
      {text:"<4人"},
      {text:"5人"},
      {text:"6人"},
      {text:"7人"},
      {text:"8人以上"}
    ]
  },
  {
    title:"标签",
    content:[
      {text:"全部"},
      {text:"本格"},
      {text:"情感"},
      {text:"欢乐"},
      {text:"硬核"},
      {text:"恐怖"}
    ]
  },
  {
    title:"类型",
    content:[
      {text:"全部"},
      {text:"公开"},
      {text:"盒装"},
      {text:"城限"},
      {text:"独家"},
      {text:"实景"}
    ]
  },
  {
    title:"店家",
    content:[
      {text:"全部"},
      {text:"热门"},
      {text:"上新"},
      {text:"推荐"},
      {text:"预告"},
      {text:"私藏"}
    ]
  },
  {
    title:"更多",
    content:[
      {text:"言情"},
      {text:"悬疑"},
      {text:"都市"},
      {text:"幻想"},
      {text:"武侠"},
      {text:"历史"}
    ]
  },
]

module.exports = {
  ificationContent
}